import {
  FaBook,
  FaBoxes,
  FaBoxOpen,
  FaBullhorn,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCashRegister,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheckSquare,
  FaFileInvoiceDollar,
  FaHandHoldingUsd,
  FaHistory,
  FaIndustry,
  FaMapMarkedAlt,
  FaMoneyBillWave,
  FaMoneyCheckAlt,
  FaPhoneAlt,
  FaReceipt,
  FaSeedling,
  FaShip,
  FaShippingFast,
  FaShoppingCart,
  FaStore,
  FaTachometerAlt,
  FaTruckLoading,
  FaUser,
  FaUserFriends,
  FaUserPlus,
  FaUsers,
  FaWallet,
  FaWarehouse,
  FaUserCog,
  FaClock,
  FaExclamationTriangle,
  FaListAlt,
} from "react-icons/fa";
import { MdAdminPanelSettings, MdDashboard } from "react-icons/md";
import { useAuthStore } from "../store/authStore";
const role =
  useAuthStore
    .getState()
    ?.authUser?.roleName?.toLowerCase()
    .replace(/\s+/g, "-") || "";

const menuConfig = [
  {
    key: "dashboard",
    title: "Dashboard",
    path: `/dashboard/${role}`,
    icon: MdDashboard,
    roles: [
      "Super Admin",
      "Admin",
      "Factory & Production Manager",
      "Factory & Production Executive",
      "Inventory Manager",
      "Inventory Executive",
      "Sales Manager",
      "Sales Executive",
      "Accounts Manager",
      "Accounts Executive",
      "Marketing Manager",
      "Marketing Executive",
      "HR Manager",
      "HR Executive",
      "POS User",
    ],
    subMenu: [],
  },

  {
    key: "hr_employee",
    title: "HR & Admin",
    path: "/hr/employees",
    icon: FaUsers,
    roles: [
      "Super Admin",
      "Admin",
      "HR Manager",
      "HR Executive",
      "Sales Manager",
      "Sales Executive",
      "Inventory Manager",
      "Inventory Executive",
      "Factory & Production Manager",
      "Factory & Production Executive",
      "Accounts Manager",
      "Accounts Executive",
      "Marketing Manager",
      "Marketing Executive",
      "POS User",
    ],
    subMenu: [
      {
        title: "Setup",
        path: "/hr/setup",
        icon: FaUserCog,
        roles: ["Super Admin", "Admin", "HR Manager", "HR Executive"],
      },
      {
        title: "Employees",
        path: "/hr/employees",
        icon: FaUser,
        roles: ["Super Admin", "Admin", "HR Manager", "HR Executive"],
      },
      {
        title: "Attendance",
        path: "/hr/attendance",
        icon: FaCalendarCheck,
        roles: ["Super Admin", "Admin", "HR Manager", "HR Executive"],
      },
      {
        title: "Attendance Summary",
        path: "/hr/attendance-summary",
        icon: FaChartBar,
        roles: [
          "Super Admin",
          "Admin",
          "HR Manager",
          "HR Executive",
          "Sales Manager",
          "Sales Executive",
          "Inventory Manager",
          "Inventory Executive",
          "Factory & Production Manager",
          "Factory & Production Executive",
          "Accounts Manager",
          "Accounts Executive",
          "Marketing Manager",
          "Marketing Executive",
          "POS User",
        ],
      },
      {
        title: "Leave Requests",
        path: "/hr/leaves/requests",
        icon: FaCalendarAlt,
        roles: [
          "Super Admin",
          "Admin",
          "HR Manager",
          "HR Executive",
          "Sales Manager",
          "Sales Executive",
          "Inventory Manager",
          "Inventory Executive",
          "Factory & Production Manager",
          "Factory & Production Executive",
          "Accounts Manager",
          "Accounts Executive",
          "Marketing Manager",
          "Marketing Executive",
          "POS User",
        ],
      },
      {
        title: "Leave Approvals",
        path: "/hr/leaves/approvals",
        icon: FaCheckSquare,
        roles: [
          "Super Admin",
          "Admin",
          "HR Manager",
          "Accounts Manager",
          "Sales Manager",
          "Inventory Manager",
          "Factory & Production Manager",
          "Marketing Manager",
        ],
      },
      {
        title: "Overtime",
        path: "/hr/overtime",
        icon: FaClock,
        roles: [
          "Super Admin",
          "Admin",
          "HR Manager",
          "Accounts Manager",
          "Sales Manager",
          "Inventory Manager",
          "Factory & Production Manager",
          "Marketing Manager",
        ],
      },
      {
        title: "Payroll",
        path: "/hr/payroll",
        icon: FaWallet,
        roles: [
          "Super Admin",
          "Admin",
          "Accounts Manager",
          "Accounts Executive",
        ],
      },
      {
        title: "Payroll Approvals",
        path: "/hr/payroll/approvals",
        icon: FaWallet,
        roles: ["Super Admin", "Admin", "Accounts Manager"],
      },
      {
        title: "My Payslips",
        path: "/hr/payroll/payslips",
        icon: FaWallet,
        roles: [
          "Super Admin",
          "Admin",
          "HR Manager",
          "HR Executive",
          "Sales Manager",
          "Sales Executive",
          "Inventory Manager",
          "Inventory Executive",
          "Factory & Production Manager",
          "Factory & Production Executive",
          "Accounts Manager",
          "Accounts Executive",
          "Marketing Manager",
          "Marketing Executive",
          "POS User",
        ],
      },
      {
        title: "Roles & Permissions",
        path: "/hr/permissions",
        icon: MdAdminPanelSettings,
        roles: ["Super Admin", "Admin"],
      },
      {
        title: "Live Tracking",
        path: "/dashboard/live-tracking",
        icon: FaMapMarkedAlt,
        roles: ["Super Admin", "Admin"],
      },
    ],
  },
  {
    key: "procurement_manufacturing",
    title: "Procurement & Manufacturing",
    path: "/procurement/pre-orders",
    icon: FaIndustry,
    roles: [
      "Super Admin",
      "Admin",
      "Factory & Production Manager",
      "Factory & Production Executive",
    ],
    subMenu: [
      {
        title: "Stakeholder Directory",
        path: "/procurement/suppliers",
        icon: FaUserPlus,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
        ],
      },
      {
        title: "Pre-Orders",
        path: "/procurement/pre-orders",
        icon: FaSeedling,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
        ],
      },
      {
        title: "Local Purchase",
        path: "/procurement/local-purchase",
        icon: FaStore,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
        ],
      },
      {
        title: "Import",
        path: "/procurement/import",
        icon: FaShip,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
        ],
      },
      {
        title: "Goods Received",
        path: "/procurement/goods-received",
        icon: FaTruckLoading,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
        ],
      },
      {
        title: "Goods Received Approvals",
        path: "/procurement/goods-received-approvals",
        icon: FaCheckSquare,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
        ],
      },
    ],
  },
  {
    key: "inventory",
    title: "Inventory Management",
    path: "/inventory",
    icon: FaWarehouse,
    roles: ["Super Admin", "Admin", "Inventory Manager", "Inventory Executive"],
    subMenu: [
      {
        title: "Overview",
        path: "/inventory",
        icon: FaChartPie,
        roles: [
          "Super Admin",
          "Admin",
          "Inventory Manager",
          "Inventory Executive",
        ],
      },
      {
        title: "Damage & Loss",
        path: "/inventory/damage-loss",
        icon: FaExclamationTriangle,
        roles: [
          "Super Admin",
          "Admin",
          "Inventory Manager",
          "Inventory Executive",
        ],
      },
      {
        title: "Quotation Calculator",
        path: "/inventory/quotation-calculator",
        icon: FaFileInvoiceDollar,
        roles: [
          "Super Admin",
          "Admin",
          "Inventory Manager",
          "Inventory Executive",
        ],
      },
    ],
  },

  {
    key: "order_sales",
    title: "Order & Sales Management",
    path: "/sales/pos",
    icon: FaShoppingCart,
    roles: [
      "Super Admin",
      "Admin",
      "Sales Manager",
      "Sales Executive",
      "POS User",
    ],
    subMenu: [
      {
        title: "POS Sale",
        path: "/sales/pos",
        icon: FaCashRegister,
        roles: ["Super Admin", "Admin", "POS User"],
      },
      {
        title: "POS Sales History",
        path: "/sales/pos-history",
        icon: FaHistory,
        roles: [
          "Super Admin",
          "Admin",
          "Sales Manager",
          "Sales Executive",
          "POS User",
        ],
      },
      {
        title: "Packaged Sale",
        path: "/sales/packaged",
        icon: FaBoxOpen,
        roles: ["Super Admin", "Admin", "Sales Manager", "Sales Executive"],
      },
      {
        title: "Packaged Sales History",
        path: "/sales/packaged-history",
        icon: FaHistory,
        roles: ["Super Admin", "Admin", "Sales Manager", "Sales Executive"],
      },
      {
        title: "Bulk Sale",
        path: "/sales/bulk",
        icon: FaBoxes,
        roles: ["Super Admin", "Admin", "Sales Manager", "Sales Executive"],
      },
      {
        title: "Bulk Sales History",
        path: "/sales/bulk-history",
        icon: FaHistory,
        roles: ["Super Admin", "Admin", "Sales Manager", "Sales Executive"],
      },
    ],
  },

  {
    key: "accounts_finance",
    title: "Accounts & Finance",
    path: "/accounts/invoices",
    icon: FaMoneyBillWave,
    roles: ["Super Admin", "Admin", "Accounts Manager", "Accounts Executive"],
    subMenu: [
      {
        title: "Invoices",
        path: "/sales/invoices",
        icon: FaReceipt,
        roles: [
          "Super Admin",
          "Admin",
          "Sales Manager",
          "Sales Executive",
          "POS User",
        ],
      },
      {
        title: "Due Payments",
        path: "/sales/partial-invoices",
        icon: FaFileInvoiceDollar,
        roles: [
          "Super Admin",
          "Admin",
          "Sales Manager",
          "Sales Executive",
          "POS User",
        ],
      },
      {
        title: "Payments Received",
        path: "/accounts/payments-received",
        icon: FaHandHoldingUsd,
        roles: [
          "Super Admin",
          "Admin",
          "Accounts Manager",
          "Accounts Executive",
        ],
      },
      {
        title: "Payments Made",
        path: "/accounts/payments-made",
        icon: FaMoneyCheckAlt,
        roles: [
          "Super Admin",
          "Admin",
          "Accounts Manager",
          "Accounts Executive",
        ],
      },
      {
        title: "Expenses",
        path: "/accounts/expenses",
        icon: FaReceipt,
        roles: [
          "Super Admin",
          "Admin",
          "Accounts Manager",
          "Accounts Executive",
        ],
      },

      {
        title: "Ledger/Transactions",
        path: "/accounts/ledger",
        icon: FaBook,
        roles: [
          "Super Admin",
          "Admin",
          "Accounts Manager",
          "Accounts Executive",
        ],
      },
    ],
  },
  {
    key: "marketing",
    title: "Marketing & Business Development",
    path: "/marketing/leads",
    icon: FaBullhorn,
    roles: [
      "Super Admin",
      "Admin",
      "Factory & Production Manager",
      "Factory & Production Executive",
      "Inventory Manager",
      "Inventory Executive",
      "Sales Manager",
      "Sales Executive",
      "Accounts Manager",
      "Accounts Executive",
      "Marketing Manager",
      "Marketing Executive",
      "HR Manager",
      "HR Executive",
      "POS User",
    ],
    subMenu: [
      {
        title: "Leads",
        path: "/marketing/leads",
        icon: FaUserPlus,
        roles: [
          "Super Admin",
          "Admin",
          "Marketing Manager",
          "Marketing Executive",
        ],
      },
      {
        title: "Market Updates",
        path: "/marketing/market-updates",
        icon: FaChartBar,
        roles: [
          "Super Admin",
          "Admin",
          "Marketing Manager",
          "Marketing Executive",
        ],
      },

      {
        title: "Visit Management",
        path: "/marketing/visit-management",
        icon: FaMapMarkedAlt,
        roles: [
          "Super Admin",
          "Admin",
          "Factory & Production Manager",
          "Factory & Production Executive",
          "Inventory Manager",
          "Inventory Executive",
          "Sales Manager",
          "Sales Executive",
          "Accounts Manager",
          "Accounts Executive",
          "Marketing Manager",
          "Marketing Executive",
          "HR Manager",
          "HR Executive",
          "POS User",
        ],
      },
      {
        title: "Follow-up",
        path: "/marketing/follow-up",
        icon: FaPhoneAlt,
        roles: [
          "Super Admin",
          "Admin",
          "Marketing Manager",
          "Marketing Executive",
        ],
      },
    ],
  },
  {
    key: "reports",
    title: "Reports and Analytics",
    path: "/reports/sales",
    icon: FaChartPie,
    roles: [
      "Super Admin",
      "Admin",
      "Sales Manager",
      "Inventory Manager",
      "Inventory Executive",
      "Factory & Production Manager",
      "Accounts Manager",
      "Accounts Executive",
    ],
    subMenu: [
      {
        title: "Sales Reports",
        path: "/reports/sales",
        icon: FaChartLine,
        roles: ["Super Admin", "Admin", "Sales Manager"],
      },
      {
        title: "Inventory Reports",
        path: "/reports/inventory",
        icon: FaBoxes,
        roles: [
          "Super Admin",
          "Admin",
          "Inventory Manager",
          "Inventory Executive",
        ],
      },
      {
        title: "Procurement Reports",
        path: "/reports/procurement",
        icon: FaIndustry,
        roles: ["Super Admin", "Admin", "Factory & Production Manager"],
      },
      {
        title: "KPI/Performance Reports",
        path: "/reports/kpi",
        icon: FaTachometerAlt,
        roles: ["Super Admin", "Admin", "Sales Manager"],
      },
    ],
  },
];

export default menuConfig;
